# Using the Node.js runtime used in the project as a parent image
FROM node:18.15.0

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the frontend code to the working directory
COPY frontend/ .

# Expose the port the app runs on
EXPOSE 3000

# Command to run the frontend app
CMD ["npm", "start"]
