# Use an the Node.js runtime used in the project as a parent image
FROM node:18.15.0

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY backend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the backend code to the working directory
COPY backend/ .

# Expose the port the app runs on
EXPOSE 3001

# Command to run the backend app
CMD ["npm", "start"]
