version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend  # Path to the backend Dockerfile
    ports:
      - "3001:3001"  # Map host port 3001 to container port 3001
    volumes:
      - ./backend:/app/backend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend  # Path to the frontend Dockerfile
    ports:
      - "3000:3000"  # Map host port 3000 to container port 3000
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend  # Frontend depends on backend

